[package]
name = "pfc-treasurechest"
description = "distrubutes 'rewards' to token holders"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
rust-version = { workspace = true }

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
serde = {workspace=true}
schemars = {workspace=true }

cosmwasm-std = { workspace = true }
thiserror = { workspace = true }
cw-ownable = { workspace = true }
cw-ownable-derive = { workspace = true }
cosmwasm-schema = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
osmosis-std-derive = {workspace=true}
[dev-dependencies]
protobuf = { workspace = true }