# https://rust-lang.github.io/rustfmt
format_code_in_doc_comments = true               # nightly
group_imports               = "StdExternalCrate" # nightly
imports_granularity         = "Crate"            # nightly
match_block_trailing_comma  = true
max_width                   = 100
use_small_heuristics        = "Off"

edition = "2021"
version = "Two"

comment_width = 100

error_on_line_overflow = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true

wrap_comments = true


