[package]
name = "pfc-dust-collector-derive"
description = "Common helpers for other contracts to use pfc-dust-collectors based on DA0 DA0 'dao-macros'"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
rust-version = { workspace = true }

[lib]
proc-macro=true

[dependencies]
proc-macro2 = { workspace = true }
quote= { workspace = true }
syn={ workspace = true }
[dev-dependencies]
cosmwasm-schema = { workspace = true }
cw-ownable = { workspace = true }
