[package]
name = "pfc-astroport-reward-holder"
version = "0.2.5"
authors = ["PFC", "Valkyrie Protocol"]
edition = "2021"
description = "Definition and types for the Valkyrie"
license = "Apache-2.0"
repository = "https://github.com/PFC-Validator/PFC-fee-split"
homepage = "https://PFC.zone"
[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
#backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
serde = { workspace = true }
schemars = { workspace = true }
cosmwasm-std = { workspace = true }
cw20 = { workspace = true }
thiserror = { workspace = true }
cw-controllers = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
