[package]
name = "pfc-fee-split"
version = "0.2.3"
authors = ["PFC"]
edition = "2021"
description = "Common helpers for other contracts to use pfc-fee-split"
license = "Apache-2.0"
repository = "https://github.com/PFC-Validator/pfc-fee-split"
#homepage = "https://TBD.example.com"
#documentation = "https://TBD.example.com"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0"
cw20 = "0.15.0"
schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
