[package]
name = "pfc-fee-split"
description = "Common helpers for other contracts to use pfc-fee-split"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
rust-version = { workspace = true }


[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
cw20 = { workspace = true }
schemars ={ workspace = true }
serde = { workspace = true }
