[package]
name = "pfc-dust-collector"
description = "Common helpers for other contracts to use pfc-fee-split"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
rust-version = { workspace = true }

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
pfc-dust-collector-derive = { workspace = true }
pfc-whitelist-derive = { workspace = true }
pfc-whitelist = { workspace = true }

cosmwasm-schema = { workspace = true }
cw-ownable = { workspace = true }
cw-ownable-derive = { workspace = true }
[dev-dependencies]
serde = { workspace = true }
