[package]
name = "pfc-vault"
version = { workspace = true }
authors = ["PFC", "Valkyrie Protocol"]
edition = { workspace = true }
description = "Definition and types for the Valkyrie"
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
#backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
serde = { workspace = true }
schemars = { workspace = true }
cosmwasm-std = { workspace = true }
#cw-storage-plus = { version = "1.0.0", features = ["iterator"] }
cw20 = { workspace = true }
thiserror = { workspace = true }
cw-controllers = { workspace = true }

[dev-dependencies]
cosmwasm-schema = { workspace = true }
#cosmwasm-storage = { version = "1.0.0", features = ["iterator"] }
