[package]
name = "pfc-whitelist"
description = "Whitelist helpers"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
rust-version = { workspace = true }

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
#backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
pfc-whitelist-derive = { workspace = true }
cosmwasm-schema = { workspace = true }
# cw-address-like = "1.0.3"
cw-storage-plus = { workspace=true }
thiserror = { workspace = true }