[package]
name = "pfc-whitelist"
version = "0.1.0"
authors = ["PFC",]
edition = "2021"
description = "Whitelist helpers"
license = "Apache-2.0"
repository = "https://github.com/PFC-Validator/PFC-fee-split"
homepage = "https://PFC.zone"
[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0"
schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
pfc-whitelist-derive = {version ="0.1.0", path ="../pfc-whitelist-derive"}
cosmwasm-schema = "1.2.1"
# cw-address-like = "1.0.3"
cw-storage-plus = "1.0.1"
thiserror = "1.0.38"