[package]
name = "pfc-dust-collector-migaloo"
version = "0.1.0"
authors = ["PFC"]
edition = "2021"
description = "Common helpers for other contracts to use pfc-fee-split"
license = "Apache-2.0"
repository = "https://github.com/PFC-Validator/pfc-fee-split"
keywords   = ["cosmos", "cosmwasm"]
[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0"
schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
pfc-dust-collector-derive = {version ="0.1.0", path ="../pfc-dust-collector-derive"}
pfc-whitelist-derive = {version ="0.1.0", path ="../pfc-whitelist-derive"}
pfc-whitelist={version="0.1.0",path="../pfc-whitelist"}
pool-network= {version="2.8.1", path="../../../white-whale-core/packages/pool-network"}
cosmwasm-schema = "1.2.1"
cw-ownable = "0.5.0"
cw-ownable-derive = "0.5.0"
